package org.wordpress.aztec

/**
 * Describes styles that could be applied to text
 */
enum class TextFormat {
    FORMAT_HEADING_1,
    FORMAT_HEADING_2,
    FORMAT_HEADING_3,
    FORMAT_HEADING_4,
    FORMAT_HEADING_5,
    FORMAT_HEADING_6,
    FORMAT_BOLD,
    FORMAT_ITALIC,
    FORMAT_UNDERLINED,
    FORMAT_STRIKETHROUGH,
    FORMAT_UNORDERED_LIST,
    FORMAT_ORDERED_LIST,
    FORMAT_QUOTE,
    FORMAT_LINK,
    FORMAT_MORE,
    FORMAT_PAGE,
    FORMAT_PARAGRAPH,
    FORMAT_BIG,
    FORMAT_SMALL,
    FORMAT_SUPERSCRIPT,
    FORMAT_SUBSCRIPT,
    FORMAT_FONT,
    FORMAT_MONOSPACE
}
