version: 2.1

orbs:
  android: wordpress-mobile/android@0.0.27

jobs:
  Lint:
    executor: 
      name: android/default
      api-version: "28"
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: lint
      - run:
          name: klint
          command: ./gradlew --stacktrace ktlint
      - run:
          name: Lint
          command: ./gradlew --stacktrace lintRelease
      - android/save-gradle-cache:
          cache-prefix: lint
      - store_artifacts:
          path: aztec/build/reports
          destination: reports
  Unit Tests:
    executor: 
      name: android/default
      api-version: "28"
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: unit-tests
      - run:
          name: Unit tests
          command: ./gradlew --stacktrace -PtestsMaxHeapSize=1536m aztec:testRelease
      - android/save-gradle-cache:
          cache-prefix: unit-tests
      - android/save-test-results
  Connected Tests:
    executor: 
      name: android/default
      api-version: "28"
    steps:
      - checkout
      - android/restore-gradle-cache:
          cache-prefix: connected-tests
      - run:
          name: Build
          command: ./gradlew --stacktrace app:assembleDebug app:assembleDebugAndroidTest
      - run:
          name: Decrypt credentials
          command: openssl aes-256-cbc -md sha256 -d -in .circleci/.firebase.secrets.json.enc -out .circleci/.firebase.secrets.json -k "${FIREBASE_SECRETS_ENCRYPTION_KEY}"
      - android/firebase-test:
          key-file: .circleci/.firebase.secrets.json
          type: instrumentation
          apk-path: app/build/outputs/apk/debug/app-debug.apk
          test-apk-path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
          device: model=Nexus5X,version=26,locale=en,orientation=portrait
          project: api-project-108380595987
          timeout: 18m
      - android/save-gradle-cache:
          cache-prefix: connected-tests

workflows:
  AztecEditor-Android:
    jobs:
      - Lint
      - Unit Tests
      - Connected Tests
